# Generated by Django 4.0.6 on 2022-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_react_detail_alter_react_name_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='created_date',
        ),
    ]
