# Generated by Django 4.0.6 on 2022-08-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_menuitem_image_remove_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image2',
            new_name='image',
        ),
    ]
