# Generated by Django 4.0.6 on 2022-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lineitem_rename_date_profile_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
            ],
        ),
    ]
