# Generated by Django 4.0.6 on 2022-07-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItem',
            new_name='MenuItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lineitems',
            new_name='menu_items',
        ),
    ]
