# Generated by Django 4.0.6 on 2022-07-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
