# Generated by Django 4.0.6 on 2022-07-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_menuitem_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='car',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='courier',
            name='firstname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.courier'),
        ),
    ]
